# Generated by Django 5.2.8 on 2025-12-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='video_opcinal',
        ),
    ]
